### ISSUE TITLE
issueベース開発のレビュー依頼

### ISSUE THREAD

**Issue by wakirenpei** [wakirenpei/SmokeShift#5]
### プロジェクトのURL

https://github.com/users/wakirenpei/projects/1/views/1

### MVPリリース

- [ ] ログイン、ログアウト機能
- [ ] タバコ登録、削除、編集機能
- [ ] 喫煙記録をつけるとリアルタイムでの金額表示機能、本数表示機能、ログ表示機能
- [ ] 喫煙記録グラフチャート機能
- [ ] 禁煙記録機能
- [ ] 終了した禁煙記録機能のログ表示

### 本リリース

- [ ] 目標金額の設定
- [ ] 目標金額を達成するとLINEに通知
- [ ] LINE認証

### ほしい物リスト機能についての変更理由

本リリースの機能として、ほしい物リスト機能を挙げていましたが、ユーザーが本当にほしい物をリストに追加できない可能性を考慮した結果、目標金額の設定機能が禁煙のモチベーションを保つために十分な機能を提供できると判断しました。これにより、ほしい物リスト機能を変更しました。

**Comment by kashiwagi-rena** [comment]
ご提出ありがとうございます。
以下コメントです。

---

- Doneの欄にもissueの記載があるのですが、もう終わっているということでしょうか？
- In Progressの欄のものは今行なっているということでしょうか？
- Reactを使用されるのでしょうか？されるのであれば、現在進行形でキャッチアップはどこまで終わっているのでしょうか？

**Comment by wakirenpei** [comment]
### プロジェクトのURL

https://github.com/users/wakirenpei/projects/1/views/1

修正点
---
Doneの欄とIn Progressの欄をTodoに変更しました。


Reactのキャッチアップについて
---
動画などを軽く見て概要を掴んだ程度で、ほとんどReactのキャッチアップはできておりません。これからRUNTEQの講座などで1週間かけて学習しようと思っているのですが、10月8日までにMVPリリースをしなければなりません。このスケジュールでReactを習得し、プロジェクトを完成させるのは厳しいでしょうか？

**Comment by kashiwagi-rena** [comment]
ご提出ありがとうございます。
- 質問なのですが、なぜ「Todo」をたくさん作っておられるのですか？理由があれば共有していただきたいです。

> Reactのキャッチアップについて

こちら、私たち講師陣のおすすめは、まずRailsにてMVPを目指して、本リリースの際に少しReactを入れることです。
Reactは、学習時間を大幅に取ります。RUNTEQのReactのカリキュラムはRailsにReactを入れる形で行われているので、MVP後に時間があれば行う程度でもいいと認識しています。

**Comment by wakirenpei** [comment]
## なぜ「Todo」をたくさん作っているのか

機能ごとにタスクを分けた方が見やすいのではと思い機能ごとに分けました。


### アドバイスを元にMVPリリース時、本リリース時の機能項目を作り替えます。

## MVPリリース時

- [ ] ログイン、ログアウト機能
- [ ] タバコ登録、削除、編集機能
- [ ] 喫煙記録管理（金額表示機能、本数表示機能、ログ表示機能）
- [ ] 禁煙記録機能（金額表示機能、ログ表示機能、喫煙データからの詳細なデータを返す機能）
- [ ] 終了した禁煙記録機能のログ表示

## 本リリース時

- [ ] 目標金額の設定
- [ ] 目標金額を達成するとLINEに通知
- [ ] LINE認証
- [ ] 喫煙記録をつけるとリアルタイムでの金額表示機能、本数表示機能、ログ表示機能
- [ ] 喫煙記録グラフチャート機能


 ## 本リリース時の相談

本リリースに時の相談なのですが、機能を盛り込みすぎでしょうか？
例えば、
- [ ] 喫煙記録をつけるとリアルタイムでの金額表示機能、本数表示機能、ログ表示機能
- [ ] 喫煙記録グラフチャート機能

上記の２つの機能を消して、ユーザーのフィードバックを受けてから機能面を考える方法を取る方が妥当でしょうか？

**Comment by tmtkzk0823** [comment]
> 機能ごとにタスクを分けた方が見やすいのではと思い、機能ごとにTodo欄を作りました。

上記承知しました。
Todoに入っているissueがMVPリリースまでに実装issueという認識でお間違えないでしょうか？

> 本リリースに時の相談なのですが、機能を付けすぎでしょうか？
例えば、
 喫煙記録をつけるとリアルタイムでの金額表示機能、本数表示機能、ログ表示機能
 喫煙記録グラフチャート機能
上記の２つの機能は一旦置いておき、ユーザーのフィードバックを受けてから機能面を考える方法を取る方が妥当でしょうか？

本リリースする際の実装においては、「機能の付けすぎ」ということはありません。「この機能は実装したい」という思いがあれば基本的に実装する方向でいいと思います。その機能をある状態でユーザーからフィードバックをもらい、修正していく形がいいかと思います。

> Reactのキャッチアップについて

上記は私からも意見させていただきますね。
ReactはJSを中心に使用します。JSの表面的な部分だけでなく、「パフォーマンスの最適化」も意識する必要があります。そう考えると`JavaScriptで2~3週間``Reactで1~2週間`のキャッチアップ期間が必要かと思います。
上記の期間を考えると、卒業まで少々時間が足りないようですので、Rails中心でアプリを作成し、まずは「卒業認定」を目指した方がいいかと思います。

**Comment by wakirenpei** [comment]
> Todoに入っているissueがMVPリリースまでに実装issueという認識でお間違えないでしょうか？

はい、その認識で間違いありません。

**ではアドバイス含め改めて、MVPリリース時、本リリース時の機能項目を作ります。**

## MVPリリース時

- [ ] ログイン、ログアウト機能
- [ ] タバコ登録、削除、編集機能
- [ ] 喫煙記録管理（金額表示機能、本数表示機能、ログ表示機能）
- [ ] 禁煙記録機能（金額表示機能、ログ表示機能、喫煙データからの詳細なデータを返す機能）
- [ ] 終了した禁煙記録機能のログ表示

## 本リリース時

- [ ] 目標金額の設定
- [ ] 目標金額を達成するとLINEに通知
- [ ] LINE認証
- [ ] 喫煙記録をつけるとリアルタイムでの金額表示機能、本数表示機能、ログ表示機能
- [ ] 喫煙記録グラフチャート機能

> ReactはJSを中心に使用します。JSの表面的な部分だけでなく、「パフォーマンスの最適化」も意識する必要があります。そう考えるとJavaScriptで2~3週間``Reactで1~2週間のキャッチアップ期間が必要かと思います。
上記の期間を考えると、卒業まで少々時間が足りないようですので、Rails中心でアプリを作成し、まずは「卒業認定」を目指した方がいいかと思います。

アドバイスありがとうございます。Rails中心でアプリを作成したのち、本リリース時に時間に応じてReactまで挑戦してみようと思います。

## プロジェクトのURL

https://github.com/users/wakirenpei/projects/1/views/1

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下MVP後で良いかと思ったカードになります。

- パスワード再設定
